### ISSUE TITLE
Cannot scroll an use all features of Effect menu item in small screen

### ISSUE THREAD

**Issue by tailetan** [Syxton/moodle-tiny_sketch#16]
Currently, we cannot scroll an use all features of Effect menu item in small screen. Please refer to the below attachment:
I believe the root cause is that the "**Insert Sketch**" button overlaps with both the "Effect" menu and the **sidebar_right** section.

![2024-11-27_13h40_12](https://github.com/user-attachments/assets/aa25fa59-d230-4973-abc9-0bb297710eeb)

CC: @Syxton

**Comment by Syxton** [comment]
@tailetan I have just pushed a fix for this.  https://github.com/Syxton/moodle-tiny_sketch/commit/55e9b88a7ffd0719b34bb57e4bbdeaa235eaf986

Let me know if this works for you.

**Comment by tailetan** [comment]
@Syxton Yes, it looks good now. I am wondering if you could apply similar CSS to .sidebar_right as well.
It should look like this:
```
.wrapper .sidebar_right {
    max-height: calc(100vh - 120px) !important;
}
```
Hope this makes sense?

**Comment by Syxton** [comment]
@tailetan I have added additional height fixes including mobile in my latest commits.  I think this should be fixed now.  Thank you for letting me know.
