### ISSUE TITLE
can you make the styles.css class a bit more specific?

### ISSUE THREAD

**Issue by danmarsden** [Syxton/moodle-tiny_sketch#4]
https://github.com/Syxton/tinymce_sketch/blob/255821aa958156f505b64d69f17ca844502a7b64/styles.css#L1

"sketch_iframe" is pretty generic - I can see this potentially being used in other places that don't use your plugin.

you might want to rename it to something like "tinymce_sketch-iframe" so that it can't accidentally clash with other usage.

**Comment by Syxton** [comment]
Fixed
