### ISSUE TITLE
Sketch "hijacks" the Context Menu

### ISSUE THREAD

**Issue by lwiere** [Syxton/moodle-tiny_sketch#7]
Hi,

first of all, thank you for this useful plugin.
We noticed that as soon as we activate the Sketch plugin in Moodle, the "normal" context menu that shows on right-click is not available any more and gets overruled by Sketch. So instead of getting the options for copy, paste etc. the new context menu only offers to open Sketch:

![image](https://github.com/Syxton/moodle-tiny_sketch/assets/134299385/2e89cfb1-38e7-4d06-b156-cf04a7339cfa)

A lot of our users don't work with keyboard shortcuts, but use the mouse and the context menu for copy & paste operations.

Any chance you can make this configurable, so we can decide if we want the Sketch context menu or the default context menu?

Many thanks,
Lena

**Comment by Syxton** [comment]
@lwiere Thank you for the report.  After looking into this, I'm not really sure what the Sketch plugin is doing that is any different than other plugins that add to the contextmenu.  In fact, when I disable the Sketch plugin, I don't get a contextmenu at all which is really strange because I know I have a few other plugins installed that "should" be in the list.  like tiny/plugins/media
And when I disable all the "extra" tiny plugins I don't get a standard context menu at all.

What version of Moodle are you currently running?

**Comment by Syxton** [comment]
@lwiere for some reason it just occurred to me that you might be asking to see the "regular" context menu as in the browser's context menu.  TinyMCE overwrites the event for a standard right click and at this point there isn't an option to disable it, however if you hold Ctrl button and right click, it will fire an alternate event which should produce the "regular" context menu.

**Comment by lwiere** [comment]
@Syxton Thanks for getting back. Yes, we indeed want to show the "regular" browser context menu, since the more common use case for people is to open the browser context menu and not to access Sketch.
The issue with the described behaviour is, that especially the users that aren't tech-savvy are the ones that go through the context menu for copy & paste operations. Instructing all users to now use CTRL + right-click for the context menu doesn't seem feasible.

In our setup, Sketch is the only plugin that shows this behaviour, so I wasn't aware that other TinyMCE plugins do the same. Would you say then this is a TinyMCE issue in general and they should make the TinyMCE vs. browser context menu configurable?

Oh, and we are an Moodle 4.2.3 Build 20231020 at the moment.

Cheers,
Lena

**Comment by Syxton** [comment]
@lwiere Yes, I think that is exactly what needs to happen.  That or Moodle makes it configurable.  I think either could do it.

**Comment by pvdublo7** [comment]
Hi,

Has there been an update on this question / issue? My teachers need the standard right-click browser Context menu. Having Sketch as the only right-click option is not working for us. I may have to uninstall until this is corrected. Would appreciate this. The above comments are spot-on - particularly, getting the Admin option to toggle on or off the right-click option.

**Comment by Syxton** [comment]
I believe this is fixed in the new 4.4.1 release I'm finalizing now.
